name: UpdateTrailers

on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout repository content
      - name: Checkout repository content
        uses: actions/checkout@v2

      # Step 2: Setup Python environment
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Step 4: Create Python script from secret
      - name: Create Python script from secret
        run: |
          echo "${{ secrets.UPDATE_TRAILER }}" > temp_script.py

      # Step 5: Run the Python script
      - name: Run API check script
        run: python temp_script.py

      # Step 6: Configure Git
      - name: Configure Git
        run: |
          git config --local user.email "${{ secrets.MY_GIT_EMAIL }}"
          git config --local user.name "junioralive"

      # Step 7: Commit files
      - name: Commit updated files
        run: |
          git add trailers.json
          git commit -m "Updated API Status" || echo "No changes to commit"

      # Step 8: Push changes
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
