name: UpdateTrailers

on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Create Python script from secret
        run: |
          echo "$UPDATE_TRAILER" > temp_script.py
        env:
          UPDATE_TRAILER: ${{ secrets.UPDATE_TRAILER }}

      - name: Run API check script
        run: python temp_script.py

      - name: commit files
        run: |
          git config --local user.email ${{ secrets.MY_GIT_EMAIL }}
          git config --local user.name "junioralive"
          git add trailers.json
          git commit -m "Updated Trailers" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
