name: UpdateTrailers

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Check out repository content
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Step 4: Create Python script from a secret
      - name: Create Python script
        run: |
          echo "${{ secrets.UPDATE_TRAILER }}" > temp_script.py

      # Step 5: Run the Python script
      - name: Run API check script
        run: python temp_script.py

      # Step 6: Commit updated files
      - name: Commit changes
        run: |
          git config --local user.email "${{ secrets.MY_GIT_EMAIL }}"
          git config --local user.name "${{ secrets.MY_GIT_USERNAME }}"
          git add trailers.json
          git commit -m "Updated trailers.json [Automated]"

      # Step 7: Push changes to the repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
